trigger: 
  - main 
pool: default

steps:

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'My_SONAR'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'new-project'
    cliProjectName: 'new-project'
    cliSources: '.'
- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'My_SONAR'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'first-pipeline_ReactTodoUIMonolith.git_dcbd241d-4f7c-4d44-94bb-6fac70a3e9c1'
    cliProjectName: 'new-project'
    cliSources: '.'
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'




- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
    failTaskOnFailureToPublishResults: true
